name = "JiL"
uuid = "20193457-2d4f-441d-9a0a-984def152164"
version = "0.1.0"
authors = ["António Menezes Leitão <antonio.menezes.leitao@gmail.com>"]

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Unicode = "1.11.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
